/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ms.usuario.services;

import ms.usuario.model.Usuario;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-16T19:05:52.542Z")

@Api(value = "usuarioByNIF", description = "the usuarioByNIF API")
public interface UsuarioByNIFApi {

    @ApiOperation(value = "Obtener usuario por NIF", notes = "Busqueda de la informacion de un alumno con su NIF", response = Usuario.class, tags={ "Usuario", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operacion realizada con exito", response = Usuario.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/usuarioByNIF/{NIF}",
        method = RequestMethod.GET)
    ResponseEntity<Usuario> usuarioByNIFNIFGet(@ApiParam(value = "NIF del usuario",required=true ) @PathVariable("NIF") String NIF);

}
