/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ms.alumno.services;

import ms.alumno.model.Pago;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-16T19:24:41.547Z")

@Api(value = "pagosByNIFyNumero", description = "the pagosByNIFyNumero API")
public interface PagosByNIFyNumeroApi {

    @ApiOperation(value = "Eliminar pago por NIF y numero", notes = "", response = Void.class, tags={ "Pago", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Operacion realizada con exito", response = Void.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/pagosByNIFyNumero/{NIF}/{number}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> pagosByNIFyNumeroNIFNumberDelete(@ApiParam(value = "NIF del alumno",required=true ) @PathVariable("NIF") String NIF,@ApiParam(value = "numero de pago",required=true ) @PathVariable("number") String number);


    @ApiOperation(value = "Actualizar pago por NIF y numero", notes = "", response = Void.class, tags={ "Pago", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Operacion realizada con exito", response = Void.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/pagosByNIFyNumero/{NIF}/{number}",
        method = RequestMethod.PUT)
    ResponseEntity<Void> pagosByNIFyNumeroNIFNumberPut(@ApiParam(value = "NIF del alumno",required=true ) @PathVariable("NIF") String NIF,@ApiParam(value = "numero de pago",required=true ) @PathVariable("number") String number,@ApiParam(value = "Objeto JSON del contenido del pago" ,required=true )  @Valid @RequestBody Pago pago);

}
