/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.swagger.api;

import com.swagger.model.Asignatura;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-14T09:20:41.795Z")

@Api(value = "asignaturaById", description = "the asignaturaById API")
public interface AsignaturaByIdApi {

    @ApiOperation(value = "Eliminar asignatura por ID", notes = "Eliminar la asignatura de la base de datos por su ID", response = Void.class, tags={ "Asignatura", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Operacion realizada con exito", response = Void.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/asignaturaById/{ID}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> asignaturaByIdIDDelete(@ApiParam(value = "ID de la asignatura",required=true ) @PathVariable("ID") Integer ID);


    @ApiOperation(value = "Obtener asignatura por ID", notes = "Busqueda de la informacion de una asignatura con su ID", response = Asignatura.class, tags={ "Asignatura", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operacion realizada con exito", response = Asignatura.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/asignaturaById/{ID}",
        method = RequestMethod.GET)
    ResponseEntity<Asignatura> asignaturaByIdIDGet(@ApiParam(value = "ID de la asignatura",required=true ) @PathVariable("ID") Integer ID);


    @ApiOperation(value = "Actualizar asignatura por ID", notes = "Actualizacion de la informacion de una asignatura.", response = Void.class, tags={ "Asignatura", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Operacion realizada con exito", response = Void.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/asignaturaById/{ID}",
        method = RequestMethod.PUT)
    ResponseEntity<Void> asignaturaByIdIDPut(@ApiParam(value = "ID de la asignatura que se quiere actualizar",required=true ) @PathVariable("ID") Integer ID,@ApiParam(value = "Objeto JSON del contenido de la asignatura" ,required=true )  @Valid @RequestBody Asignatura asignatura);

}
