/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ms.profesor.services;

import ms.profesor.model.Departamento;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-16T19:13:21.767Z")

@Api(value = "departamentoByCode", description = "the departamentoByCode API")
public interface DepartamentoByCodeApi {

    @ApiOperation(value = "Eliminar departamento por codigo", notes = "", response = Void.class, tags={ "Departamento", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Operacion realizada con exito", response = Void.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/departamentoByCode/{code}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> departamentoByCodeCodeDelete(@ApiParam(value = "Codigo del departamento",required=true ) @PathVariable("code") Integer code);


    @ApiOperation(value = "Obtener la matricula de un alumno de un anno especifico", notes = "Devuelve la matricula con una lista de codigos de las asignaturas  matriculadas.", response = Departamento.class, tags={ "Departamento", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operacion realizada con exito", response = Departamento.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/departamentoByCode/{code}",
        method = RequestMethod.GET)
    ResponseEntity<Departamento> departamentoByCodeCodeGet(@ApiParam(value = "Codigo del departamento",required=true ) @PathVariable("code") Integer code);


    @ApiOperation(value = "Actualizar departamento por codigo", notes = "", response = Void.class, tags={ "Departamento", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Operacion realizada con exito", response = Void.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/departamentoByCode/{code}",
        method = RequestMethod.PUT)
    ResponseEntity<Void> departamentoByCodeCodePut(@ApiParam(value = "Codigo del departamento",required=true ) @PathVariable("code") Integer code,@ApiParam(value = "Objeto JSON del contenido del departamento" ,required=true )  @Valid @RequestBody Departamento departamento);

}
