/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ms.profesor.services;

import ms.profesor.model.Departamento;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-16T19:13:21.767Z")

@Api(value = "departamento", description = "the departamento API")
public interface DepartamentoApi {

    @ApiOperation(value = "Dar de alta un departamento", notes = "", response = Void.class, tags={ "Departamento", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Operacion realizada con exito", response = Void.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/departamento",
        method = RequestMethod.POST)
    ResponseEntity<Void> departamentoPost(@ApiParam(value = "Objeto JSON del contenido del departamento" ,required=true )  @Valid @RequestBody Departamento departamento);

}
