/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ms.profesor.services;

import ms.profesor.model.Nomina;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-16T19:13:21.767Z")

@Api(value = "nominaByNIF", description = "the nominaByNIF API")
public interface NominaByNIFApi {

    @ApiOperation(value = "Eliminar nomina por NIF y numero", notes = "", response = Void.class, tags={ "Nomina", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Operacion realizada con exito", response = Void.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/nominaByNIF/{NIF}/{number}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> nominaByNIFNIFNumberDelete(@ApiParam(value = "NIF del profesor",required=true ) @PathVariable("NIF") Integer NIF,@ApiParam(value = "Fecha de la nomina",required=true ) @PathVariable("number") Integer number);


    @ApiOperation(value = "Obtener la nomina de un profesor por numero", notes = "", response = Nomina.class, tags={ "Nomina", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operacion realizada con exito", response = Nomina.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/nominaByNIF/{NIF}/{number}",
        method = RequestMethod.GET)
    ResponseEntity<Nomina> nominaByNIFNIFNumberGet(@ApiParam(value = "NIF del profesor",required=true ) @PathVariable("NIF") Integer NIF,@ApiParam(value = "Fecha de la nomina",required=true ) @PathVariable("number") Integer number);


    @ApiOperation(value = "Actualizar noimina por NIF y numero", notes = "", response = Void.class, tags={ "Nomina", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Operacion realizada con exito", response = Void.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/nominaByNIF/{NIF}/{number}",
        method = RequestMethod.PUT)
    ResponseEntity<Void> nominaByNIFNIFNumberPut(@ApiParam(value = "NIF del profesor",required=true ) @PathVariable("NIF") Integer NIF,@ApiParam(value = "Fecha de la nomina",required=true ) @PathVariable("number") Integer number,@ApiParam(value = "Objeto JSON del contenido de la nomina" ,required=true )  @Valid @RequestBody Nomina departamento);

}
