/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ms.reserva.services;

import ms.reserva.model.ReservaGrupo;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-16T19:10:53.003Z")

@Api(value = "reservasByGrupo", description = "the reservasByGrupo API")
public interface ReservasByGrupoApi {

    @ApiOperation(value = "Obtener la nomina de un grupo por numero", notes = "", response = ReservaGrupo.class, responseContainer = "List", tags={ "ReservaGrupo", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operacion realizada con exito", response = ReservaGrupo.class, responseContainer = "List"),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/reservasByGrupo/{code}",
        method = RequestMethod.GET)
    ResponseEntity<List<ReservaGrupo>> reservasByGrupoCodeGet(@ApiParam(value = "codigo del grupo",required=true ) @PathVariable("code") Integer code);

}
