/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ms.matricula.services;

import ms.matricula.model.Asignatura;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-16T19:17:33.453Z")

@Api(value = "asignaturasMatriculablesByAlumno", description = "the asignaturasMatriculablesByAlumno API")
public interface AsignaturasMatriculablesByAlumnoApi {

    @ApiOperation(value = "Obtener las asignaturas de cada carrera", notes = "Busqueda de la asignaturas por carrera", response = Asignatura.class, responseContainer = "List", tags={ "Asignatura", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operacion realizada con exito", response = Asignatura.class, responseContainer = "List"),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/asignaturasMatriculablesByAlumno/{NIF}",
        method = RequestMethod.GET)
    ResponseEntity<List<Asignatura>> asignaturasMatriculablesByAlumnoNIFGet(@ApiParam(value = "NIF del alumno",required=true ) @PathVariable("NIF") String NIF);

}
