-- MySQL Script generated by MySQL Workbench
-- mar 14 nov 2017 22:41:46 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema UVisa2017
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `UVisa2017` ;

-- -----------------------------------------------------
-- Schema UVisa2017
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UVisa2017` DEFAULT CHARACTER SET utf8 ;
USE `UVisa2017` ;

-- -----------------------------------------------------
-- Table `UVisa2017`.`Carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Carrera` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Carrera` (
  `codigo` INT NOT NULL,
  `facultad` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `numero_creditos` INT GENERATED ALWAYS AS (num_cred_opt+num_cred_tran+num_cred_obl) VIRTUAL,
  `num_cred_opt` INT NULL,
  `num_cred_tran` INT NULL,
  `num_cred_obl` INT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_carrera_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Asignatura` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Asignatura` (
  `codigo` INT NOT NULL,
  `creditos` INT NOT NULL,
  `tipo` ENUM('transversal', 'optativa', 'obligatoria') NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `carrera` INT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_asignatura_UNIQUE` (`codigo` ASC),
  INDEX `fk_Asignatura_Carrera1_idx` (`carrera` ASC),
  CONSTRAINT `fk_Asignatura_Carrera1`
    FOREIGN KEY (`carrera`)
    REFERENCES `UVisa2017`.`Carrera` (`codigo`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Alumno` (
  `num_expediente` INT NOT NULL,
  `id` INT NOT NULL,
  `carrera` INT NOT NULL,
  `NIF` INT NOT NULL COMMENT 'NIF se utiliza para poder iniciar la sesión, la tupla se identifica por ID.',
  `cc` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `tipo_user` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_1` VARCHAR(45) NOT NULL,
  `apellido_2` VARCHAR(45) NOT NULL,
  `banco` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `num_expediente_UNIQUE` (`num_expediente` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_Alumno_Carrera1_idx` (`carrera` ASC),
  CONSTRAINT `fk_Alumno_Carrera1`
    FOREIGN KEY (`carrera`)
    REFERENCES `UVisa2017`.`Carrera` (`codigo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Departamento` (
  `nombre` INT NOT NULL,
  `codigo` INT NOT NULL,
  `carga` INT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Categoria` (
  `horas_semanales` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Profesor` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Profesor` (
  `antiguedad` INT NULL,
  `num_tramos_investigacion` INT NULL,
  `num_tramos_docentes` INT NULL,
  `id` INT NOT NULL,
  `departamento` INT NULL,
  `NIF` INT NOT NULL COMMENT 'NIF se utiliza para poder iniciar la sesión, la tupla se identifica por ID.',
  `cuenta` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `tipo_user` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_1` VARCHAR(45) NOT NULL,
  `apellido_2` VARCHAR(45) NOT NULL,
  `banco` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `categoria`),
  INDEX `fk_Profesor_Departamento1_idx` (`departamento` ASC),
  INDEX `fk_Profesor_Categoria1_idx` (`categoria` ASC),
  CONSTRAINT `fk_Profesor_Departamento1`
    FOREIGN KEY (`departamento`)
    REFERENCES `UVisa2017`.`Departamento` (`codigo`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Profesor_Categoria1`
    FOREIGN KEY (`categoria`)
    REFERENCES `UVisa2017`.`Categoria` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Administrador` (
  `id` INT NOT NULL,
  `NIF` INT NOT NULL COMMENT 'NIF se utiliza para poder iniciar la sesión, la tupla se identifica por ID.',
  `cuenta` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `tipo_user` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_1` VARCHAR(45) NOT NULL,
  `apellido_2` VARCHAR(45) NOT NULL,
  `banco` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Nomina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Nomina` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Nomina` (
  `numero` INT NOT NULL,
  `fecha` DATE NULL,
  `importe` DOUBLE NULL,
  `profesor` INT NOT NULL,
  PRIMARY KEY (`numero`, `profesor`),
  INDEX `fk_Nomina_Profesor1_idx` (`profesor` ASC),
  CONSTRAINT `fk_Nomina_Profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `UVisa2017`.`Profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Matricula` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Matricula` (
  `promocion` INT NOT NULL,
  `reservado` TINYINT(1) NOT NULL,
  `alumno` INT NOT NULL,
  PRIMARY KEY (`promocion`, `alumno`),
  INDEX `fk_Matricula_Alumno1_idx` (`alumno` ASC),
  CONSTRAINT `fk_Matricula_Alumno1`
    FOREIGN KEY (`alumno`)
    REFERENCES `UVisa2017`.`Alumno` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Pago` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Pago` (
  `importe` DOUBLE NOT NULL,
  `numero_pago` INT NOT NULL,
  `pagado` TINYINT(1) NOT NULL,
  `promocion` INT NOT NULL,
  `alumno` INT NOT NULL,
  PRIMARY KEY (`numero_pago`),
  UNIQUE INDEX `numero_pago_UNIQUE` (`numero_pago` ASC),
  INDEX `fk_Pago_Matricula1_idx` (`promocion` ASC, `alumno` ASC),
  CONSTRAINT `fk_Pago_Matricula1`
    FOREIGN KEY (`promocion` , `alumno`)
    REFERENCES `UVisa2017`.`Matricula` (`promocion` , `alumno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Grupo` (
  `asignatura` INT NOT NULL,
  `id` INT NOT NULL,
  `actas` TINYINT(1) NULL,
  INDEX `fk_Grupo_Asignatura1_idx` (`asignatura` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Grupo_Asignatura1`
    FOREIGN KEY (`asignatura`)
    REFERENCES `UVisa2017`.`Asignatura` (`codigo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Espacio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Espacio` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Espacio` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `aforo_max` INT NULL,
  `precio_alquiler` DOUBLE NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`ReservaProfesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`ReservaProfesor` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`ReservaProfesor` (
  `fecha` DATE NOT NULL,
  `hora_entrada` INT NOT NULL,
  `espacio` INT NOT NULL,
  `importe` INT NOT NULL,
  `profesor` INT NOT NULL,
  `hora_salida` INT NOT NULL,
  PRIMARY KEY (`fecha`, `hora_entrada`, `espacio`),
  INDEX `fk_ReservaProfesores_Espacio1_idx` (`espacio` ASC),
  INDEX `fk_ReservaProfesores_Profesor1_idx` (`profesor` ASC),
  CONSTRAINT `fk_ReservaProfesores_Espacio1`
    FOREIGN KEY (`espacio`)
    REFERENCES `UVisa2017`.`Espacio` (`codigo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ReservaProfesores_Profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `UVisa2017`.`Profesor` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`ReservaGrupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`ReservaGrupo` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`ReservaGrupo` (
  `hora_entrada` INT NOT NULL,
  `hora_salida` INT NOT NULL,
  `dia_semana` INT NOT NULL,
  `espacio` INT NOT NULL,
  `grupo` INT NOT NULL,
  PRIMARY KEY (`hora_entrada`, `dia_semana`, `espacio`),
  INDEX `fk_ReservaGrupo_Espacio1_idx` (`espacio` ASC),
  INDEX `fk_ReservaGrupo_Grupo1_idx` (`grupo` ASC),
  CONSTRAINT `fk_ReservaGrupo_Espacio1`
    FOREIGN KEY (`espacio`)
    REFERENCES `UVisa2017`.`Espacio` (`codigo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ReservaGrupo_Grupo1`
    FOREIGN KEY (`grupo`)
    REFERENCES `UVisa2017`.`Grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Matricula_Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Matricula_Grupo` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Matricula_Grupo` (
  `Mpromocion` INT NOT NULL,
  `alumno` INT NOT NULL,
  `grupo` INT NOT NULL,
  `nota` INT NULL,
  PRIMARY KEY (`Mpromocion`, `alumno`, `grupo`),
  INDEX `fk_Matricula_has_Grupo_Grupo1_idx` (`grupo` ASC),
  INDEX `fk_Matricula_has_Grupo_Matricula1_idx` (`Mpromocion` ASC, `alumno` ASC),
  CONSTRAINT `fk_Matricula_has_Grupo_Matricula1`
    FOREIGN KEY (`Mpromocion` , `alumno`)
    REFERENCES `UVisa2017`.`Matricula` (`promocion` , `alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_has_Grupo_Grupo1`
    FOREIGN KEY (`grupo`)
    REFERENCES `UVisa2017`.`Grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UVisa2017`.`Profesor_Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UVisa2017`.`Profesor_Grupo` ;

CREATE TABLE IF NOT EXISTS `UVisa2017`.`Profesor_Grupo` (
  `profesor` INT NOT NULL,
  `grupo` INT NOT NULL,
  PRIMARY KEY (`profesor`, `grupo`),
  INDEX `fk_Profesor_has_Grupo_Grupo1_idx` (`grupo` ASC),
  INDEX `fk_Profesor_has_Grupo_Profesor1_idx` (`profesor` ASC),
  CONSTRAINT `fk_Profesor_has_Grupo_Profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `UVisa2017`.`Profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_has_Grupo_Grupo1`
    FOREIGN KEY (`grupo`)
    REFERENCES `UVisa2017`.`Grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `UVisa2017` ;

-- -----------------------------------------------------
-- Placeholder table for view `UVisa2017`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UVisa2017`.`Reservas` (`espacio` INT, `hora_entrada` INT, `hora_salida` INT, `dia_semana` INT);

-- -----------------------------------------------------
-- Placeholder table for view `UVisa2017`.`CargaDocente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UVisa2017`.`CargaDocente` (`id` INT);

-- -----------------------------------------------------
-- View `UVisa2017`.`Reservas`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `UVisa2017`.`Reservas` ;
DROP TABLE IF EXISTS `UVisa2017`.`Reservas`;
USE `UVisa2017`;
CREATE  OR REPLACE VIEW `Reservas` AS select espacio, hora_entrada, hora_salida, dia_semana 
							from ReservaProfesor
							union (select espacio, hora_entrada, hora_salida, DAYOFWEEK(fecha) as dia_semana from ReservaGrupo);

-- -----------------------------------------------------
-- View `UVisa2017`.`CargaDocente`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `UVisa2017`.`CargaDocente` ;
DROP TABLE IF EXISTS `UVisa2017`.`CargaDocente`;
USE `UVisa2017`;
CREATE  OR REPLACE VIEW `CargaDocente` AS (select nombre as nombre_departamento, carga_docente 
								from Departamento 
                                join (select departamento, id, (select COUNT(*)*2 from Profesor_Grupo where profesor = id) as carga_docente from Profesor group by departamento)
                                on codigo = departamento);
SET SQL_MODE = '';
GRANT USAGE ON *.* TO Admin;
 DROP USER Admin;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'Admin' IDENTIFIED BY 'isa2017';

GRANT ALL ON `UVisa2017`.* TO 'Admin';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `UVisa2017`.* TO 'Admin';
GRANT EXECUTE ON ROUTINE `UVisa2017`.* TO 'Admin';
GRANT SELECT, INSERT, TRIGGER ON TABLE `UVisa2017`.* TO 'Admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
