/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ms.profesor.services;

import ms.profesor.model.Profesor;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-16T19:13:21.767Z")

@Api(value = "profesorByNIF", description = "the profesorByNIF API")
public interface ProfesorByNIFApi {

    @ApiOperation(value = "Eliminar profesor por NIF", notes = "Eliminar la cuenta de un profesor por NIF", response = Void.class, tags={ "Profesor", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Operacion realizada con exito", response = Void.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/profesorByNIF/{NIF}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> profesorByNIFNIFDelete(@ApiParam(value = "NIF del profesor",required=true ) @PathVariable("NIF") String NIF);


    @ApiOperation(value = "Obtener profesor por NIF", notes = "Busqueda de la informacion de un profesor con su NIF", response = Profesor.class, tags={ "Profesor", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operacion realizada con exito", response = Profesor.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/profesorByNIF/{NIF}",
        method = RequestMethod.GET)
    ResponseEntity<Profesor> profesorByNIFNIFGet(@ApiParam(value = "NIF del profesor",required=true ) @PathVariable("NIF") String NIF);


    @ApiOperation(value = "Actualizar profesor", notes = "Actualizacion de la informacion de la cuenta de un profesor", response = Void.class, tags={ "Profesor", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Operacion realizada con exito", response = Void.class),
        @ApiResponse(code = 405, message = "Operacion sin realizar", response = Void.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Void.class) })
    
    @RequestMapping(value = "/profesorByNIF/{NIF}",
        method = RequestMethod.PUT)
    ResponseEntity<Void> profesorByNIFNIFPut(@ApiParam(value = "NIF del profesor que se quiere actualizar",required=true ) @PathVariable("NIF") String NIF,@ApiParam(value = "Objeto JSON del contenido del profesor" ,required=true )  @Valid @RequestBody Profesor alumno);

}
